gpg:
  install_path: "${SystemDrive}\\Scoop\\apps\\gnupg\\current"
  # Before gnupg 2.3.2 release home directory could be properly link-ed
  #   homedir: "${USERPROFILE}\\Scoop\\apps\\gnupg\\current\\home"
  # With gnupg 2.3.3 release (due to the changes in T5537) use this instead
  #   homedir: "${USERPROFILE}\\Scoop\\persist\\gnupg\\home"
  #   socketdir: ""
  # After gnupg 2.3.4 release we have to switch to
  homedir: "${SystemDrive}\\Scoop\\apps\\gnupg\\current\\home"
  socketdir: "${SystemDrive}\\Scoop\\apps\\gnupg\\current\\gnupg"
gui:
  debug: false
  setenv: true
  openssh: native
  # Use line below to enable SSH_AUTH_SOCK to point to cygwin socket
  #   openssh: cygwin

